homepage:
    path: /
    controller: App\Infraestructure\Controller\HomePage:__invoke

modalwebcam:
    path: /modalWebcam/{permalink}
    controller: App\Infraestructure\Controller\ModalWebcam:__invoke