services:
    _defaults:
        autoconfigure: true
        autowire: true
    
    # Configure
    _instanceof:
        App\Shared\Domain\Bus\Command\CommandHandler:
            tags: ['command_handler']
        
        App\Shared\Domain\Bus\Query\QueryHandler:
            tags: ['query_handler']


    App\Shared\:
        resource: '../src/Shared'

    # Wire
    App\:
        resource: '../src/'
        exclude:
            - '../src/Shared/'
            - '../src/Kernel.php'
            - '../src/Domain/Entity'

    App\Infraestructure\Controller\:
        resource: '../src/Infraestructure/Controller'
        tags: [ 'controller.service_arguments' ]


    # -- APP DEFINITIONS --
    # Command/Query Handlers
    App\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
        arguments: [!tagged command_handler]
    
    App\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
        arguments: [!tagged query_handler]

    # -- IMPLEMENTATIONS SELECTOR --
    App\Shared\Domain\Bus\Query\QueryBus: '@App\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus'
    App\Shared\Domain\Bus\Command\CommandBus: '@App\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus'